### ISSUE TITLE
Introduction Doc UI has no left spaces

### ISSUE THREAD

**Issue by coder-abdo** [franken-ui/ui#11]
the `Introduction` Document on the `Franken-UI` web page does not has enough left spacing I explain this problem with screenshots.
![Screenshot from 2024-07-15 21-55-51](https://github.com/user-attachments/assets/4c6ac792-ed92-4335-b24b-20a3ebd72308)
![Screenshot from 2024-07-15 21-55-26](https://github.com/user-attachments/assets/a52ca276-63a5-47ec-840a-fda587c888ae)

**Comment by sveltecult** [comment]
Hello,

Hello, would you mind sharing your device and browser information? Unfortunately, I can only test on a handful of devices: 2 Android phones and 1 Windows. So far, I have seen no issues. These should be the expected results:

Desktop (`xl:*`)

![image](https://github.com/user-attachments/assets/45bcfc2c-4802-4b7f-ae5c-3aad7ba60a91)

Large (`lg:*`)

![Screen Shot 2024-07-16 at 06 24 54](https://github.com/user-attachments/assets/5c5a21c4-d4d3-48ce-8ada-fb7f56c718e8)

Medium (`md:*`)

![Screen Shot 2024-07-16 at 06 25 43](https://github.com/user-attachments/assets/b2b8aa98-2fc9-4743-b893-505e792040d8)

Small (`sm:*`)

![Screen Shot 2024-07-16 at 06 26 30](https://github.com/user-attachments/assets/2e5b76ed-3d48-48ae-88b9-167962b3c548)

Extra small (default)

![Screen Shot 2024-07-16 at 06 26 58](https://github.com/user-attachments/assets/d13987d4-6506-4eb9-92a4-18823384643f)

Sharing your device info might help me spot the issue and potentially fix it.

**Comment by coder-abdo** [comment]
here is my setup 
- HP notebook with 15 inch
- Linux Ubuntu 22.04 operator system.
- Google Chrome browser.

**Comment by sveltecult** [comment]
🚀 Changed to `14rem`. Thanks guys!
