### ISSUE TITLE
cdn link for blue theme is broken

### ISSUE THREAD

**Issue by sangyongjung** [franken-ui/ui#13]
On `https://franken-ui.dev/docs/installation#installation-via-cdn`

```
<link
  rel="stylesheet"
  href="https://unpkg.com/franken-wc@0.0.2/dist/css/blue.min.css"
/>
```
is broken as `https://unpkg.com/franken-wc@0.0.2/dist/css/blue.min.css` is unavailable.
I tried other colors (themes) and every other color works fine.

**Comment by sveltecult** [comment]
🚀 fixed on `v0.0.4`
