### ISSUE TITLE
Installation Guide on Laravel Blade

### ISSUE THREAD

**Issue by mariio46** [franken-ui/ui#15]
hi @sveltecult,
i really appreciate your work on [Franken UI](https://franken-ui.dev/). but can you give us installation guide on Laravel please. because, for the first time i read your docs, it seems i have little bit confused when trying to implement things on my Laravel application.

**Comment by sveltecult** [comment]
Hello, what part of the docs are you confused?

You can try and explore this Laravel template: https://github.com/sveltecult/franken-ui-template-laravel this is a little bit outdated but everything is pretty much the same.

**Comment by mariio46** [comment]
i've been read your docs completely and i can understand now. Massive thanks for providing this UI, is really helped me on my current project. especially [Overlay](https://franken-ui.dev/docs/overlay) and [Select](https://franken-ui.dev/docs/select) components. Hoping to see search functionality on your docs ASAP.

**Comment by sveltecult** [comment]
Great! Glad that it helped your project. Should you have any questions, just let me know. Closing this for now.
