### ISSUE TITLE
npm error Cannot read properties of null (reading 'matches')

### ISSUE THREAD

**Issue by kuntal-c** [franken-ui/ui#17]
npm i tailwindcss postcss franken-ui && npx franken-ui init -p

npm error Cannot read properties of null (reading 'matches')

**Comment by sveltecult** [comment]
Hello @kuntal-c 

What is your setup? Like, what framework are you using, or are you using Vite? I just run it and it works just fine. Please be more specific so I can help you.

Here's a short demo I posted a while back https://x.com/sveltecult/status/1810776685392142691 it still works. You can also try CDN and upgrade to proper build later on your development.
