### ISSUE TITLE
Components request

### ISSUE THREAD

**Issue by bevenky** [franken-ui/ui#25]
Have a request for the following components within this framework and also make it work with fasthtml that uses htmx for interactive UI. Happy to sponsor this entire thing to fast track the development. Can also discuss this over email if that's easier.

Shadcn components
- Date picker with all options (timepicker within datepicker and seperate)
- DataTable
- Input
- Input OTP
- Navigation Menu
- Scroll Area
- Toggle & Toggle Groups
- Charts

Shadcn type blocks, themes & colors

- Additional components
    - Autocomplete
        - Text
        - With icon
    - Input Phone (with country code and flag as options)
    - Codeblock

- Support advanced datagrids like agrid
- Drag and drop node based flow editor functionality like reactflow

Making this work with fasthtml that uses htmx

**Comment by sveltecult** [comment]
Hello @bevenky 

We can talk about this via email `sveltecult[at]proton[dot]me`.

Thanks.

**Comment by sveltecult** [comment]
Hello Venky!

Thanks for reaching out about Franken UI. I'd like to start by addressing your question about FastHTML compatibility - I'm not familiar with FastHTML specifically, but Franken UI is already at its lowest level, which is standard HTML and web components. This means it can be used with any backend framework that renders HTML, and it's also compatible and has first-party support for HTMX.

Regarding the components you've requested, here's a breakdown:

- Existing components: I already have Input, Input OTP, Toggle & Toggle Groups (via icon button and iconnav). If you need customizations for these, just let me know.
- Planned components: These components are already planned: Datepicker, Navigation Menu, Shadcn Blocks (with the recently added colors), Autocomplete / Autosuggest, Phone input with flags, and Charts.
- Custom solutions: Components like Datatable, Datagrids, Flow editor, and Autocomplete with icon are quite advanced, and some of these are new to me. This might be better suited for a custom solution. Franken UI was initially designed for small teams and solo devs, so some of these components might be more suitable for private collaboration.

As the sole maintainer of this project, I'm happy to discuss custom solutions with you. If you're interested, we can talk about the rate and I can work full-time on this project. I can also add your company logo as a sponsor if you'd like.

Let me know how you'd like to proceed.

Regards,
Reden ***@***.***)

Sent with [Proton Mail](https://proton.me/) secure email.
