### ISSUE TITLE
uk-select `error` attribute does nothing

### ISSUE THREAD

**Issue by BeMoreDog** [franken-ui/ui#28]
Im using:
```
  <link rel="stylesheet" href="https://unpkg.com/franken-ui@1.1.0/dist/css/core.min.css" />
  <script src="https://unpkg.com/franken-ui@1.1.0/dist/js/core.iife.js" type="module"></script>
  <script src="https://unpkg.com/franken-ui@1.1.0/dist/js/icon.iife.js" type="module"></script>
```

and applying `error` to a `uk-select` seems to have no effect.  I expected a red danger state on the select?

```
<uk-select error uk-cloak>
      <option value="option1">Option 1</option>
      <option value="option2">Option 2</option>
      <option value="option3">Option 3</option>
      <option value="option4">Option 4</option>
      <option value="option5">Option 5</option>
    </uk-select>
```

**Comment by Kaoschuks** [comment]
I would love an answer to this also @sveltecult

**Comment by BeMoreDog** [comment]
> Please eloborate, why you expect that applying error to a uk-select, results in red color?
> 
> Have you read that in the docs?

Yes, the docs say:
>To indicate an error state in the form, simply add the error attribute. This will apply a “danger” state to the component, providing visual feedback to the user.

And unless I'm missing something no visual feedback is applied.  The example in the docs has some manually (as far as I can tell) added text above and below.

**Comment by Kaoschuks** [comment]
I have this error only when I try to render ul-select option dynanimcally

**Comment by sveltecult** [comment]
The original shadcn design does not have red color unless you **focus** on that element.
