### ISSUE TITLE
Example html pages

### ISSUE THREAD

**Issue by Dixith-dev** [franken-ui/ui#29]
Hey @sveltecult ! 😊, I just want to say I absolutely love your work! I'm really enjoying learning and working with your open source library. I have a quick question—it's not an issue, just curiosity. Do you happen to have the example pages from the Astro examples repo available in plain HTML by any chance?

I remember one of my teammates managing to get a page into HTML before, but since I'm still getting the hang of things, I could use a little help figuring it out. Thanks a ton in advance!

**Comment by fabcp** [comment]
Just have a look here: 🙂
https://examples.franken-ui.dev/examples/mail
https://examples.franken-ui.dev/examples/dashboard
https://examples.franken-ui.dev/examples/cards
https://examples.franken-ui.dev/examples/tasks
https://examples.franken-ui.dev/examples/playground
https://examples.franken-ui.dev/examples/music
https://examples.franken-ui.dev/examples/authentication
