### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by ainsleyclark** [franken-ui/ui#30]
Hi there,

Will charts be generally available at some point?

Thank you!

**Comment by Firdavs-coder** [comment]
Same question

**Comment by sveltecult** [comment]
> Will charts be generally available at some point?

It is definitely planned. Unfortunately, 2 projects that supposed to use this framework got cancelled many months ago but I still managed to make it to 1.0 and finish check list.

Without any real project to work on or at least support from the community, I may not be able to do it for now. But it's on my priority list so don't worry.

**Comment by Kaoschuks** [comment]
I am using fraken on two of my projects.
They are built with angular https://fromlabeladmin.web.app/insights is a sample @ainsleyclark I used some chart library here and @sveltecult we can work together to create more components and templates more rich than even shadcn
