### ISSUE TITLE
postcss config for media query

### ISSUE THREAD

**Issue by medfata** [franken-ui/ui#34]
Hi 
i m facing an issue in when building tailwind css file with the franken plugin, using this postcss.config.cjs:

> 
> module.exports = {
> 	plugins: [
> 		require('tailwindcss'),
> 		require('franken-ui/postcss/sort-media-queries')({
> 			sort: 'mobile-first'
> 		}),
> 		require('franken-ui/postcss/combine-duplicated-selectors')({
> 			removeDuplicatedProperties: true
> 		})
> 	]
> };

the issue is that the media query css is placed above the default css, which breaks the styles of franken components.
**here is an example of the uk-stepper:**
![image](https://github.com/user-attachments/assets/1aba0aec-3688-4cae-97fa-c5014cf4ac13)

**It should be like the following (from the franken-ui documentation website):**
![image](https://github.com/user-attachments/assets/af8fd400-9be2-4f64-9cac-c312e232d656)

**Anyone faced this issue  ?**

**Comment by sveltecult** [comment]
Hello,

Make sure you install postcss in your project. I indicated on the upgrade guide that it's optional but I saw last minute that I did not change anything. My mistake 😅.
