### ISSUE TITLE
Link not working in dropdown

### ISSUE THREAD

**Issue by vbrvk** [franken-ui/ui#38]
If dropdown contains link element (like in this example https://franken-ui.dev/examples/dashboard), link not triggered on click
It can be easy reproduced by changing link target to "/", it will not trigger url change on click
<img width="491" alt="image" src="https://github.com/user-attachments/assets/e5aa0f54-2086-479b-8f73-e6be20a59430">

It caused by event listeners on dropdown element
<img width="337" alt="image" src="https://github.com/user-attachments/assets/e940d2bf-4ebc-42a0-92c6-2792f4bd4f74">

If listeners made passive (with dev tools) - then link triggered as expected

**Comment by sveltecult** [comment]
Remove your `uk-drop-close` class
