### ISSUE TITLE
Theme switcher doesn't remember light / dark settings

### ISSUE THREAD

**Issue by aboutjquery** [franken-ui/ui#42]
I'm using v1, and according to the documentation I added the following code
```
document.addEventListener("DOMContentLoaded", function() {
const htmlElement = document.documentElement;

if (
localStorage.getItem("mode") === "dark" ||
(!("mode" in localStorage) &&
window.matchMedia("(prefers-color-scheme: dark)").matches)
) {
htmlElement.classList.add("dark");
} else {
htmlElement.classList.remove("dark");
}

htmlElement.classList.add(localStorage.getItem("theme") || "uk-theme-zinc");
});
```

I added DOMContentLoaded, which should have no effect, but I added it in html

`<body class="bg-background text-foreground">`

and

```
<div class="uk-inline">
 <button class="uk-icon-button uk-icon-button-small uk-icon-button-outline">
 <uk-icon icon="palette" uk-cloak></uk-icon>
 </button>
 <div
 class="uk-card uk-card-body uk-card-default uk-drop uk-width-large"
 uk-drop="mode: click; offset: 8"
 >
 <div class="uk-card-title uk-margin-medium-bottom">Customize</div>
 <uk-theme-switcher></uk-theme-switcher>
 </div>
</div>
```

What happens now is that when I open the theme selector and select Rose and Dark, for example, and then I press F5 to reload the page, the page is indeed Rose + Dark, but the theme selector is now selecting Rose + Light.

```
<button class="uk-active">
 <uk-icon class="uk-margin-small-right" icon="sun"></uk-icon>
 Light
 </button>
```

The color is remembered but the light and dark are not. Also, how do I remove unnecessary themes? For example, I want to remove Rose, or just leave Zinc. I can't find it in the documentation. If it already exists, please let me know. I know, thank you for writing such a convenient html version. Sometimes I need to use it in wordpress php, which is very convenient. Author, do you think it is a good idea to use franken-ui in wordpress? Thanks you

**Comment by sveltecult** [comment]
> Also, how do I remove unnecessary themes? 

This is only for v2.0
