### ISSUE TITLE
Where are the unminified web components?

### ISSUE THREAD

**Issue by sangrepura** [franken-ui/ui#44]
I downloaded `https://unpkg.com/franken-ui@1.1.0/dist/js/core.iife.js`

But I have been unsuccessful in locating these web components anywhere in this org or github.  Where are these published in their un-minified format?

for example `<uk-theme-switcher>`

**Comment by sveltecult** [comment]
You mean the source code? It will go live here https://github.com/franken-ui/webc probably next month.
